kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-reader-role-binding
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "dora-metrics.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  -
    kind: ServiceAccount
    name: {{ include "dora-metrics.fullname" . }}
    namespace: {{ .Release.Namespace }}